//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCuaToiASPNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheLoaiSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheLoaiSP()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int ID { get; set; }
        public string TenLoaiSP { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> idLoaiCuaTheLoaiSP { get; set; }
    
        public virtual LoaiCuaTheLoaiSP LoaiCuaTheLoaiSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
